[tools]
bun = "1"

[tasks.prettify]
run = "bunx prettier . --write"

[tasks.uglify]
run = [
    "bunx terser client/useweft-0.2.0.js -c -m -o client/latest.js",
    "gzip --keep --force client/latest.js > client/latest.js.gz"
]

[tasks.deploy]
depends = ["uglify"]
run = "bunx wrangler pages deploy ."
